from setuptools import setup, find_packages

setup(name='mockingbird',
      version='1.0',
      description='Turns structured data into unstructured data, such as docx or pdf files.',
      url='https://www.github.com/openraven/mockingbird',
      author='Open Raven Team',
      author_email='opensource@openraven.com',
      install_requires=['openpyxl==3.0.5',
                        'RandomWords==0.3.0',
                        'pyyaml==5.3.1',
                        'pyexcel-ods==0.6.0',
                        'python-docx==0.8.10',
                        'requests==2.25.0',
                        'reportlab==3.5.59',
                        'python-pptx==0.6.18',
                        'pandas==1.2.1',
                        'pandavro==1.6.0',
                        'python-pptx==0.6.18',
                        'pyspark==3.0.1'],
      license='apache',
      entry_points={'console_scripts': ['mockingbird_cli=mockingbird.__command_line:main']},
      packages=find_packages(),
      include_package_data=True,
      zip_safe=False,
      classifiers=[
          "Development Status :: 5 - Production/Stable",
          "License :: OSI Approved :: Apache Software License",
          "Programming Language :: Python :: 3.9",
      ],
      )
